#!/bin/bash

ENTRY_DIR="/usr/local/bin/terminalsearch"

if [ -z "$1" ]; then
  echo "Usage: $(basename "$0") <subcommand> [arguments...]"
  exit 1
fi

SUBCOMMAND="$1"
shift

SUBCOMMAND_SCRIPT="$ENTRY_DIR/$SUBCOMMAND"

if [ ! -x "$SUBCOMMAND_SCRIPT" ]; then
  echo "Subcommand not found or not executable: $SUBCOMMAND_SCRIPT"
  exit 2
fi

"$SUBCOMMAND_SCRIPT" "$@"
